### ISSUE TITLE
Create TApp and TApp Detail states Fixed TEA payment per 1000 blocks but paid miners per 100 blocks

### ISSUE THREAD

**Issue by joelchen** [tearust/teaproject#101]
Create TApp states Fixed TEA payment per 1000 blocks:
<img width="428" alt="Screenshot 2021-11-22 at 1 13 43 AM" src="https://user-images.githubusercontent.com/6938607/142772429-b50fca35-5f61-4645-baf8-5a08548c8451.png">

TApp Detail states Fixed TEA payment per 1000 blocks
<img width="865" alt="Screenshot 2021-11-22 at 1 18 47 AM" src="https://user-images.githubusercontent.com/6938607/142772439-22750c36-a4e6-45b6-bcda-33b7a10c5b5c.png">
:

However, it turns out to be payment per 100 blocks, as written in https://github.com/tearust/teaproject/wiki/Mining:-Staked-TApp-Tokens and https://github.com/tearust/teaproject/wiki/TApps---Creating-a-TApp.

It was tapp_id 4 activated at block 26144, lost almost 7000 TEAs until sold all tokens to stop the bleed at block 31078.

**Comment by kevingzhang** [comment]
1000 blocks will be in the real block chain but 100 blocks in our current "fast mode". Fast mode is for the contest only.
Once the main net starts, it will be per 1000 blocks.

We did not change the UI because we do not want to miss the change and let it to the main net.

**Comment by kevingzhang** [comment]
in fast mode, almost everything is 10 times faster

**Comment by joelchen** [comment]
@kevingzhang Your comment in discussion and interview mentioned 100 times: https://github.com/tearust/teaproject/discussions/44#discussioncomment-1223727

**Comment by kevingzhang** [comment]
you are right. the life span is 100x faster but the reward is 10x faster. the workload would be too high if we issued reward every 10 blocks
