### ISSUE TITLE
资产数据不一致

### ISSUE THREAD

**Issue by nick-yin** [tearust/teaproject#107]
我的My investment里的资产要比leader board里的多，见图，我唯一投资的TAPP 6号 Mine faster，现在净资产市值 80224.17，但在Leader board表里的Tapp token balance里资产是80216.12

![1638292376355](https://user-images.githubusercontent.com/6196649/144095412-b40782bf-55e0-4b75-9b4e-8263758e5ad0.jpg)
5
![1638292368227](https://user-images.githubusercontent.com/6196649/144095431-a1fea8c4-7720-4838-9f37-dc1308de8060.jpg)
3

**Comment by kevingzhang** [comment]
@liyangwood Can you verify the algorithm of the leader board, including the source of data. Try to find out the differences between those two UI pages. why are the data different?

**Comment by liyangwood** [comment]
Both data returned from layer1.
@raindust 
please help to check.

**Comment by raindust** [comment]
@nick-yin 这两个值不一致正常，可能的原因有两个：
1. "My investment in Tapp"里统计的balance包括用TEA投资tapp amount, 以及自己以旷工身份host tapp而产生到的质押tapp amount这两个部分。而“Leader board”中只包含前者，所以请检查是否自己有在Host该Tapp
2. 两个列表中的tapp balance都是根据当前tapp的市场价（即1一个Tapp token等于多少个TEA）来预估的数值，即便不存在1中的问题，有可能在你查看两个页面的时候由于其他人对该Tapp的行为造成了当前市场价格的波动，因此预估的数值也不一样

**Comment by kevingzhang** [comment]
我们打算把投资的token和host得到的token分开两个栏目在leaderboard中展示. 这样就容易解释了

**Comment by nick-yin** [comment]
最好能把HOST收益和投资收益分开显示，这两个数据如果很清晰实时，能指导矿工的投资操作
