### ISSUE TITLE
The planted tea tree C has no profit.

### ISSUE THREAD

**Issue by harodggg** [tearust/teaproject#110]
When epoch 7 started, I planted 2 tea trees of type c. But 6 hours passed without any gains.

**Comment by harodggg** [comment]
![image](https://user-images.githubusercontent.com/31732456/145859929-af035663-2ce9-4eae-bbe9-7fc30e2cd814.png)

**Comment by raindust** [comment]
Thanks for reporting, fixed in https://github.com/tearust/delegator-resources/commit/88f636946e739ab465bf95a624021781ea334138

**Comment by raindust** [comment]
To solve this quickly, user should update following: https://github.com/tearust/delegator-resources/tree/epoch7#update-new-versionhttps://github.com/tearust/delegator-resources/tree/epoch7#update-new-version
