### ISSUE TITLE
My total investment value in TEA is 0. Why?

### ISSUE THREAD

**Issue by Aha1201** [tearust/teaproject#111]
<img width="1792" alt="截屏2021-12-14 上午11 52 17" src="https://user-images.githubusercontent.com/79050187/145930334-9b60ac9e-445e-4f41-acba-7a66dd702b41.png">

**Comment by kevingzhang** [comment]
Have you invested any tapp? Invest means you use TEA to buy an TApp token. This is different than hosting the tapp.

**Comment by kevingzhang** [comment]
I can see my investment to tapp in TEA
![image](https://user-images.githubusercontent.com/1761809/145938963-8f6bcbf1-85d8-4952-9ecc-8f57855250b2.png)

So I think it is probably not a bug

**Comment by Aha1201** [comment]
> Have you invested any tapp? Invest means you use TEA to buy an TApp token. This is different than hosting the tapp.

Of course, I bought 2 TApp tokens.
