### ISSUE TITLE
Pay off loan does not pay loan and get CML back

### ISSUE THREAD

**Issue by joelchen** [tearust/teaproject#112]
Tried paying off loan on my collateral seeds (374 & 224), but they are not gotten back after screen showed transaction is successful.

https://user-images.githubusercontent.com/6938607/145944155-e9c7ef8a-e516-44bf-a169-904e9f0ff1be.mov

**Comment by kevingzhang** [comment]
@raindust I do not think we changed the front end recently. please check the RPC

**Comment by joelchen** [comment]
Related to https://github.com/tearust/Chinese-wiki/issues/12.

**Comment by liyangwood** [comment]
Outdated. closed
