### ISSUE TITLE
Unable to sell small amount of TApp token even with ample amount of TEA

### ISSUE THREAD

**Issue by joelchen** [tearust/teaproject#113]
Unable to sell small amount of TApp token even with ample amount of TEA. Could be related to https://github.com/tearust/teaproject/issues/112.

https://user-images.githubusercontent.com/6938607/145976392-3a5474ee-08b1-4169-b0f2-f416f54aab3c.mov

**Comment by joelchen** [comment]
Similar issue as https://github.com/tearust/Chinese-wiki/issues/12.

**Comment by kevingzhang** [comment]
Not sure the real cause. please take a look

**Comment by liyangwood** [comment]
It's fixed before.
can close it.
