### ISSUE TITLE
No token rewards to miners

### ISSUE THREAD

**Issue by joelchen** [tearust/teaproject#114]
For TApps 15 and 16, miners do not get any token rewards.
<img width="1082" alt="Screenshot 2021-12-15 at 3 43 57 PM" src="https://user-images.githubusercontent.com/6938607/146144931-386af8c9-0a04-4a92-8627-b797c22f4810.png">
<img width="1082" alt="Screenshot 2021-12-15 at 3 45 37 PM" src="https://user-images.githubusercontent.com/6938607/146145020-026732de-5c5d-4769-a0ae-7ab317189fe0.png">

**Comment by joelchen** [comment]
@kevingzhang This has probably got to do with reward token amount. Working TApp 14 is 99999999999, whereas failing TApps 15 and 16 are 100000000000000000000.

**Comment by kevingzhang** [comment]
@liyangwood This is bug related to the one you are looking at, the zero reward bug? I remember you mentioned about a bug that set the reward to zero due to some reason I forgot. please take a look to make sure this is not a new issue.

**Comment by liyangwood** [comment]
@raindust please filter the 0 reward records

**Comment by raindust** [comment]
Updated in epoch8
