### ISSUE TITLE
Total xxxx TEA /  yyyy Mainnet CML coupon = zzzz T/C

### ISSUE THREAD

**Issue by kevingzhang** [tearust/teaproject#116]
Total xxxx TEA /  yyyy Mainnet CML coupon = zzzz T/C 
This new sentences can show both total TEA and total Coupon at the time of snapshot. of course, the rate.
Because there would be roll over CML form last cycle, the coupon number is no longer exact 3.

_Originally posted by @kevingzhang in https://github.com/tearust/teaproject/discussions/115_

**Comment by lxm218** [comment]
Total 130747.1277 TEA/ 3.4911 Mainnet CML coupon = 37451.5562 T/C

**Comment by liyangwood** [comment]
Done
