### ISSUE TITLE
Error in epoch9 mining

### ISSUE THREAD

**Issue by anjumparvez** [tearust/teaproject#123]
There is a bug in epoch9, while I invest to buy tapp token in a tapp, it works fine, but when it time to sell tapp token, the sell amount doesn't credited to my tea balance...

**Comment by kevingzhang** [comment]
@geopor can you verify this workflow can reproduce the bug?

**Comment by geopor** [comment]
I just tried and had no issues selling TEA Party tapp tokens back to TEA. @anjumparvez which tapp token is it? If you can list it and the steps including the exact quantity you're selling we can try to reproduce

**Comment by anjumparvez** [comment]
I invested in 101 tApp, but next day while selling amount of 30000 Tea I
didn't received it in wallet back, again I sell nearly 12000 Tea, again it
didn't arrived in my wallet...

**Comment by geopor** [comment]
@anjumparvez thanks for bringing this to our attention I was able to recreate the bug you experienced. We'll raise this as an internal issue
