### ISSUE TITLE
How to provider RA as a miner?

### ISSUE THREAD

**Issue by TingALin** [tearust/teaproject#134]
What to do if I want to provider RA (Remote Attestation) to earn the tea in the future?

**Comment by kevingzhang** [comment]
RA is done by state machine nodes. 

As a miner, so far the only way to join RA mining is owning a SEAT from Harberger TApp.

When owning a SEAT, you own the revenue from the state machine represented by that SEAT. Of course, you will need to pay tax based on your own valuation on your own SEAT and pay corresponding tax. See more about Harberger tax.

At early stage, we generate UBI (Universal basic income) to regular hosting nodes besides RA profit state machine nodes. That means, if you run a hosting node, you will still get an UBI income without doing actual RA work. This will help hosting miners to cover its mining cost even there isn't a lot of gas fee income at the early stage.

Please add your comments below
