### ISSUE TITLE
USD to Coffee

### ISSUE THREAD

**Issue by kevingzhang** [tearust/teaproject#24]
### Discussed in https://github.com/tearust/teaproject/discussions/23

<div type='discussions-op-text'>

<sup>Originally posted by **leeyemi** August 17, 2021</sup>

Hi, when click the detail on leader board found below "USD"
![image](https://user-images.githubusercontent.com/88189869/129710959-e6d2af71-19c7-47fc-8ba4-aae07975f859.png)
</div>

**Comment by kevingzhang** [comment]
@liyangwood You said you did a search USD on the UI, seems you did not

**Comment by liyangwood** [comment]
fixed.
