### ISSUE TITLE
when a time (loan due, lifespan etc) is less than one day, it still shows one day. I should show XXh or YYm.

### ISSUE THREAD

**Issue by kevingzhang** [tearust/teaproject#33]
### Discussed in https://github.com/tearust/teaproject/discussions/32

<div type='discussions-op-text'>

<sup>Originally posted by **kevingzhang** August 19, 2021</sup>
when you see a time shows  1 d, it is actually not one day, it is just saying less than 1 day, it could be 10 minutes but you never know.
If it is more than 1 day, we can show 1d, but if it is less than one day, we should show XXh XXm instead.</div>

**Comment by liyangwood** [comment]
fixed, the smallest unit is hour for now.
