### ISSUE TITLE
## Include a "Type" column in the auctions list

### ISSUE THREAD

**Issue by kevingzhang** [tearust/teaproject#47]
## Include a "Type" column in the auctions list

Right now you have to click through to find out what kind of seed it is. 

<img width="1110" alt="Screen Shot 2021-08-23 at 8 30 05 AM" src="https://user-images.githubusercontent.com/86096370/130476199-ae42bae4-42b8-43cd-b03d-4990613d2486.png">

_Originally posted by @geopor in https://github.com/tearust/teaproject/discussions/46#discussioncomment-1223132_

**Comment by liyangwood** [comment]
https://github.com/tearust/tea-browser-wallet/commit/faf01c51fc601ecf8d0d697a71fd63c896f50282

**Comment by liyangwood** [comment]
done in test-net
wallet version T_0.1.61
