### ISSUE TITLE
allow highest bidder to retract his big with a penalty equals to his bid minutes the second highest bid

### ISSUE THREAD

**Issue by kevingzhang** [tearust/teaproject#48]
currently we do not allow the highest bidder to retract.
we can allow with a penalty. the penalty is the number that equals to his bid minutes the second highest bid.

so if this bidder is trying to fool the system by adding a super high bid, they will get a huge penalty too.

the penalty can goes to the DAO and burnt.

**Comment by raindust** [comment]
implement in https://github.com/tearust/tea-camellia/commit/238f419f7412c96f40bcac6b4e17b38d0de93568

I would suggest giving a warning when doing this in frontend

**Comment by liyangwood** [comment]
done in testnet

**Comment by liyangwood** [comment]
done in testnet
