### ISSUE TITLE
add a column in leader board showing how much USDT the winner will receive if as is

### ISSUE THREAD

**Issue by kevingzhang** [tearust/teaproject#49]
Currently the leader board did not show how much award a contestant can receive (if the contest ends now).
this number will be constantly change, but it can show a prediction and boost some confidence.

What do you think this column should be called?

The calculation is 
award = $1500 * contestant_total_account_value / (sigma_of_all_contestants_account_value)

@geopor add your comments on the name, then reassign this issue to @liyangwood . 
@liyangwood please fix in epoch 2.1, the on going contest.

**Comment by geopor** [comment]
We can call it: **Prize share**

**Comment by kevingzhang** [comment]
> We can call it: **Prize share**

Good. so @liyangwood please use "Prize share"

**Comment by liyangwood** [comment]
release branch https://github.com/tearust/tea-browser-wallet/commit/dda5f8b6369d39f161150ee7c6317eaab3e03e9c

**Comment by liyangwood** [comment]
master branch https://github.com/tearust/tea-browser-wallet/commit/4dc3e3546006c308b96a904ccf141db668fe509d
