### ISSUE TITLE
without top up feature, if someone running out of TEA, it won't start any new transaction. so he would be stuck.

### ISSUE THREAD

**Issue by kevingzhang** [tearust/teaproject#50]
without top up feature, if someone running out of TEA, it won't start any new transaction. so he would be stuck.

_Originally posted by @kevingzhang in https://github.com/tearust/teaproject/discussions/42_

**Comment by liyangwood** [comment]
https://github.com/tearust/tea-browser-wallet/commit/54fcfb6c0db6f4068e375d180159dfb73ea83f6f

**Comment by liyangwood** [comment]
done in test-net
