### ISSUE TITLE
Redeem coupon cost COFFEE for investors.

### ISSUE THREAD

**Issue by kevingzhang** [tearust/teaproject#55]
Investors still get coupon as we did before, but when redeem coupons, the investor need to pay
A: 2000 COFFEE
B: 1000 COFFEE
C: 500 COFFEE.

the COFFEE is paid to DAO (we original called sudo account).

Others (non investors) do not have such benefit, they have to buy seeds at the market price, likely higher than the investor coupon account.

Investor can choose not to redeem the coupon, but if the coupon expired, it expired.

This is the simulator of investor pay USDT to get CML coupon.

_Originally posted by @kevingzhang in https://github.com/tearust/teaproject/discussions/38_

**Comment by raindust** [comment]
fix in https://github.com/tearust/tea-camellia/commit/ef879ea325bbc80cf4cdee43e92cc68a6751bb4c
