### ISSUE TITLE
Delegator installation script fails on Debian 11.1 and Ubuntu 21.10

### ISSUE THREAD

**Issue by joelchen** [tearust/teaproject#82]
On Debian 11.1 and Ubuntu 21.10, `sh -c "$(curl -fsSL https://raw.githubusercontent.com/tearust/delegator-resources/master/install.sh)"` fails with the following message:
```
Package docker-ce is not available, but is referred to by another package.
```
Solution is to run the following commands (Ubuntu 21.10) before executing install.sh:
```
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu impish stable" -y
```

**Comment by kevingzhang** [comment]
@Raindust, please check if there is anything you can improve?

**Comment by kevingzhang** [comment]
@raindust any update on this?

**Comment by raindust** [comment]
We suggest using "ubuntu 18.04" or "ubuntu 20.04", if using other versions that we have not tested for a long time, we could not promise it can run properly

**Comment by kevingzhang** [comment]
added the requirement on wiki
