### ISSUE TITLE
Some CMLs cannot resume

### ISSUE THREAD

**Issue by joelchen** [tearust/teaproject#83]
In My Camellia, clicking Resume action on some CMLs (110, 152, 172, 251) that have become offline, gives the following error even when there is more than 100 TEA available, CMLs (131, 183) are alright:
<img width="975" alt="Screenshot 2021-10-26 at 12 14 34 PM" src="https://user-images.githubusercontent.com/6938607/138816430-fa82ec26-3c45-4968-9892-a4acc38dbc1e.png">

**Comment by kevingzhang** [comment]
Duplicated. The oribit db issue is handled by other issue
