### ISSUE TITLE
Activate miner page - Error message does not remind user about CML loan possibility

### ISSUE THREAD

**Issue by RyanCanuck** [tearust/teaproject#90]
![29743](https://user-images.githubusercontent.com/94243277/141654571-e0d102f6-53be-48c0-9098-9b28d9e8b8e2.jpg)

**Comment by kevingzhang** [comment]
Please update the instruction . tell users how to get the 1000 T when starts

**Comment by geopor** [comment]
Updated:
https://github.com/tearust/tea-browser-wallet/commit/46cc9671f904638819c385cd9fb5abce6c4c8b25
https://github.com/tearust/tea-browser-wallet/commit/4ee72301010a32320240579e9309d5974614b1ab
https://github.com/tearust/tea-browser-wallet/commit/bbc988a33d83b5e56b06f3984d7f6515602e89da

**Comment by kevingzhang** [comment]
@geopor Please always send these kinds of issue to @liyangwood  if you made some change and ask him to build to see it on the online UI.

This also let him know the changes.

**Comment by liyangwood** [comment]
Done

**Comment by kevingzhang** [comment]
Please verify and close when done @RyanCanuck
