### ISSUE TITLE
Activate miner page - process should check for 1000 TEA at step 1

### ISSUE THREAD

**Issue by RyanCanuck** [tearust/teaproject#94]
At the moment, the activation process for a miner checks the user's assets for 1000 TEA as part of the final stage before activating the miner. In the event the user does not have 1000 TEA, the user has to complete the CML loan process then go BACK to activation step one and re-enter all the details about their miner. The suggested edit is to check for the 1000 TEA at step one of the activation process to save the user having to repeat the entire process.

**Comment by kevingzhang** [comment]
We should check the balance **before** start planting. That means before the first scripts. 
Currently user have done half of the workflow then was asked to top up balance is bad user experience.

**Comment by liyangwood** [comment]
Done
